/**
 * Created with IntelliJ IDEA.
 * User: alvaro
 * Date: 12/02/14
 * Time: 11:53
 * To change this template use File | Settings | File Templates.
 */
object Problem44 extends App {

  /*
  Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?
   */

  def isInteger(d: Double) = Math.abs(d - d.toInt) < 0.00000001

  def p(n: Double) = n * (3 * n - 1) / 2

  def findWithUpperLimit(limit: Int) = {
    for (b <- (1 to limit - 1).view;
         a <- (b + 1 to limit).view;
         c = (Math.sqrt(36 * a * a - 12 * a - 36 * b * b + 12 * b + 1) + 1) / 6;
         d = (Math.sqrt(36 * a * a - 12 * a + 36 * b * b - 12 * b + 1) + 1) / 6
         if (isInteger(c) && isInteger(d))
    )
    yield (a, b, c, d)
  }

  findWithUpperLimit(100000).head match{ case(a,b,c,d) =>
    println(s"p($a) = ${p(a)}")
    println(s"p($b) = ${p(b)}")
    println(s"p($c) = ${p(c)}")
    println(s"p($d) = ${p(d)}")
    println(s"p($a) - p(${b}) = ${p(c)}   ${p(a)-p(b)}")
    println(s"p($a) + p(${b}) = ${p(d)}   ${p(a)+p(b)}")
  }

}
