/*

Triangle, square, pentagonal, hexagonal, heptagonal, and octagonal numbers are all figurate (polygonal) numbers and are generated by the following formulae:

Triangle	 	P3,n=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Square	 	P4,n=n2	 	1, 4, 9, 16, 25, ...
Pentagonal	 	P5,n=n(3n-1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	P6,n=n(2n-1)	 	1, 6, 15, 28, 45, ...
Heptagonal	 	P7,n=n(5n-3)/2	 	1, 7, 18, 34, 55, ...
Octagonal	 	P8,n=n(3n-2)	 	1, 8, 21, 40, 65, ...
The ordered set of three 4-digit numbers: 8128, 2882, 8281, has three interesting properties.

The set is cyclic, in that the last two digits of each number is the first two digits of the next number (including the last number with the first).
Each polygonal type: triangle (P3,127=8128), square (P4,91=8281), and pentagonal (P5,44=2882), is represented by a different number in the set.
This is the only set of 4-digit numbers with this property.
Find the sum of the only ordered set of six cyclic 4-digit numbers for which each polygonal type: triangle, square, pentagonal, hexagonal, heptagonal, and octagonal, is represented by a different number in the set.

*/

object Problem61 extends App{

  type Numero = Int
  type FamiliaDeNumeros = Seq[Numero]
  type Ciclo = List[Numero]
  
  
  
  def sequence( generator: (Numero)=>Numero ) = Iterator.from(1).map( generator )
  
  val min = 1000
  val max = 9999

  val triangles = sequence( n => n*(n+1)/2 )
  val squares = sequence( n => n*n )
  val pentagons = sequence( n => n*(3*n-1)/2 )
  val hexagons = sequence( n => n*(2*n-1) )
  val heptagons = sequence( n => n*(5*n-3)/2 )
  val octagons = sequence( n => n*(3*n-2) )
  
  val originals = List( triangles, squares, pentagons, hexagons, heptagons, octagons )
  
  
  val permutations = originals.
                     map( _.dropWhile( _<min  ).takeWhile( _<=max ).toSeq ).
                     permutations
  
  def cyclicSet( sets: List[FamiliaDeNumeros] ) = {

    def valid( a: Numero, b: Numero ) = a.toString.drop(2) == b.toString.take(2)

    def findLineal( current: List[Numero], remainingSets: List[ FamiliaDeNumeros ] ) : Option[Ciclo]= {
      if( remainingSets.size == 0 ){
        if( valid( current.last, current.head ) ){
          Some(current)
        }
        else{
          None
        }
      }
      else{

        val currentSet = remainingSets.head
        val nextSets = remainingSets.tail
        def valid_( n: Numero ) = current.size == 0 || valid( current.last, n)
        val ret = currentSet.
                  filter( n => valid_( n ) ).
                  map( n => findLineal( current :+n, nextSets ) ).
                  find( _.isDefined )
                  
        ret match{
          case None => None
          case Some(r) => r
        }
      }
    }
    
    findLineal( Nil, sets )
  }
  
  val solution = permutations.
                 map( sets => cyclicSet(sets) ).
                 find( _.isDefined ).
                 get.
                 getOrElse( Nil )
                
                 
                 
  // (8256, 5625, 2512, 1281, 8128, 2882)               
  println( s"\nSolution:$solution ${solution.sum}")
}